-- SELECT 
--     Customers.CustomerName,
--     Orders.OrderID
-- FROM Orders
-- FULL OUTER JOIN Customers
-- ON Customers.CustomerID=Orders.CustomerID 
-- ;

-- NOT ALLOWED


-- THEORY
-- IN CASE OF FULL OUTER JOIN ALTHOUGH IT'S NOT ALLOWED FOR SOME SPECIFIC DATABASES BUT THE THEORY BEHIND THAT IS WHATEVER THE VALUE IS THAT MATCHED BETWEEN BOTH OR UNMATCHED OR WHATEVER IT'S GONNA GIVE EACH AND EVERY DATA SO IT'S NOT SO MEANING FULL TO GET ALL UNNECESSARY RANDOM DATAS SHOW THESE ARE NOT ALLOWED... 